import  Metadata from "next";
import ComplexNavbar from "./components/Nav1"
import "./globals.css";
 import Footer  from "./components/Footer";
import { ThemeProvider } from "./material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ThemeProvider>
    <html lang="en">
      <body
        // biome-ignore lint/style/noUnusedTemplateLiteral: <explanation>
        className={`antialiased`}
      >
      <ComplexNavbar />
        {children}
        <Footer />
      </body>
    </html>
    </ThemeProvider>
  );
}
